feat: modify git pre-commit

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -1,15 +1,29 @@
-#!/bin/bash
+#!/bin/sh
+JS_STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")
 
-# 确保将要提交的所有 JavaScript 代码通过 standard 规范的检查
-function xargs-r() {
-  # Portable version of "xargs -r". The -r flag is a GNU extension that
-  # prevents xargs from running if there are no input files.
-  if IFS= read -r -d '' path; then
-    { echo -n "$path"; echo -ne "\0"; cat; } | xargs $@
+PASS=true
+
+# Check for eslint
+if [[ "$JS_STAGED_FILES" != "" ]]; then
+  echo "\nValidating Javascript:\n"
+
+  node ./node_modules/.bin/eslint $JS_STAGED_FILES
+
+  if [[ "$?" == 0 ]]; then
+    echo "\033[32mESLint Passed\033[0m"
+  else
+    echo "\033[41mESLint Failed\033[0m"
+    PASS=false
   fi
-}
-git diff -z --name-only --cached --relative | grep -z '\.jsx\?$' | xargs-r -0 -t standard
-if [[ $? -ne 0 ]]; then
-  echo 'JavaScript Standard Style errors were detected. Aborting commit.'
-  exit 1
+
+  echo "\nJavascript validation completed!\n"
 fi
+
+if ! $PASS; then
+  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint and Scss-lint but do not. Please fix the ESLint and Scss-lint errors and try again.\n"
+  exit 1
+else
+  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
+fi
+
+exit $?
